### ISSUE TITLE
How do I use this please sorry if my english is bad?

### ISSUE THREAD

**Issue by jdoqiaw** [tranphuquy19/DuolingoBotExtension#1]

**Comment by tranphuquy19** [comment]
This extension is not available now, but you can try by install extension [Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo ), then copy all content of [this file](https://github.com/tranphuquy19/DuolingoBotExtension/blob/master/src/javascript/index.js) to Tampermoney user scripts [click Tampermonkey icon in address bar -> create a new script -> replace "// Your code here..." with the content of the file above]. In the settings tab, add `https://www.duolingo.com/skill*` into `Original matches textbox`

Some functions may not work now. I'm trying to improve the code. Good luck!
